import java.util.HashMap;
import java.util.Properties;

public enum ChemicalElement {
	/**
	 * Each chemical element is best represented by an enumeration, since each
	 * one is in a sequence of ascending atomic numbers.
	 */
	None, Hydrogen, Helium, Lithium, Beryllium, Boron, Carbon, Nitrogen, Oxygen, Fluorine, Neon, Sodium, Magnesium, Aluminum, Silicon, Phosphorus, Sulfur, Chlorine, Argon, Potassium, Calcium, Scandium, Titanium, Vanadium, Chromium, Manganese, Iron, Cobalt, Nickel, Copper, Zinc, Gallium, Germanium, Arsenic, Selenium, Bromine, Krypton, Rubidium, Strontium, Yttrium, Zirconium, Niobium, Molybdenum, Technetium, Ruthenium, Rhodium, Palladium, Silver, Cadmium, Indium, Tin, Antimony, Tellurium, Iodine, Xenon, Cesium, Barium, Lanthanum, Cerium, Praseodymium, Neodymium, Promethium, Samarium, Europium, Gadolinium, Terbium, Dysprosium, Holmium, Erbium, Thulium, Ytterbium, Lutetium, Hafnium, Tantalum, Tungsten, Rhenium, Osmium, Iridium, Platinum, Gold, Mercury, Thallium, Lead, Bismuth, Polonium, Astatine, Radon, Francium, Radium, Actinium, Thorium, Protactinium, Uranium, Neptunium, Plutonium, Americium, Curium, Berkelium, Californium, Einsteinium, Fermium, Mendelevium, Nobelium, Lawrencium, Rutherfordium, Dubnium, Seaborgium, Bohrium, Hassium, Meitnerium, Darmstadtium, Roentgenium, Ununbium, Ununtrium, Ununquadium, Ununpentiun, Ununhexium, Ununseptium, Ununoctium, Ununnonium, Unundecium;

	// The following method looks up an element based on an atomic number.
	public static ChemicalElement lookUpChemicalElementByOrdinal(int ordinal) {
		return ChemicalElement.values()[ordinal];
	}

	public static int findAtomicNumberByElement(ChemicalElement element) {
		int number = 0;
		while (number < 120) {
			ChemicalElement next = ChemicalElement.lookUpChemicalElementByOrdinal(number);
			if (next == element) {
				return number;
			}
		}
		return 120;
	}

	/**
	 * This HashMap associates each sequential element with the number of
	 * electrons new in orbit in its s, p, d, f orbits respectively. For
	 * example, Chromium has one less electron in its s orbit than Vanadium, but
	 * two more in its d orbit.
	 */
	static HashMap<ChemicalElement, OrbitalChangeVector> electronOrbitalMap() {
		HashMap<ChemicalElement, OrbitalChangeVector> electronOrbitalMap = new HashMap<ChemicalElement, OrbitalChangeVector>();
		electronOrbitalMap.put(ChemicalElement.Hydrogen, new OrbitalChangeVector(1, 0, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Helium, new OrbitalChangeVector(1, 0, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Lithium, new OrbitalChangeVector(1, 0, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Beryllium, new OrbitalChangeVector(1, 0, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Boron, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Carbon, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Nitrogen, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Oxygen, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Fluorine, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Neon, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Sodium, new OrbitalChangeVector(1, 0, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Magnesium, new OrbitalChangeVector(1, 0, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Aluminum, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Silicon, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Phosphorus, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Sulfur, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Chlorine, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Argon, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Potassium, new OrbitalChangeVector(1, 0, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Calcium, new OrbitalChangeVector(1, 0, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Scandium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Titanium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Vanadium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Chromium, new OrbitalChangeVector(-1, 0, 2, 0));
		electronOrbitalMap.put(ChemicalElement.Manganese, new OrbitalChangeVector(1, 0, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Iron, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Cobalt, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Nickel, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Copper, new OrbitalChangeVector(-1, 0, 2, 0));
		electronOrbitalMap.put(ChemicalElement.Zinc, new OrbitalChangeVector(1, 0, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Gallium, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Germanium, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Arsenic, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Selenium, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Bromine, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Krypton, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Rubidium, new OrbitalChangeVector(1, 0, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Strontium, new OrbitalChangeVector(1, 0, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Yttrium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Zirconium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Niobium, new OrbitalChangeVector(-1, 0, 2, 0));
		electronOrbitalMap.put(ChemicalElement.Molybdenum, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Technetium, new OrbitalChangeVector(1, 0, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Ruthenium, new OrbitalChangeVector(-1, 0, 2, 0));
		electronOrbitalMap.put(ChemicalElement.Rhodium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Palladium, new OrbitalChangeVector(-1, 0, 2, 0));
		electronOrbitalMap.put(ChemicalElement.Silver, new OrbitalChangeVector(1, 0, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Cadmium, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Indium, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Tin, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Antimony, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Tellurium, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Iodine, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Xenon, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Cesium, new OrbitalChangeVector(1, 0, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Barium, new OrbitalChangeVector(1, 0, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Lanthanum, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Cerium, new OrbitalChangeVector(0, 0, 0, 1));
		electronOrbitalMap.put(ChemicalElement.Praseodymium, new OrbitalChangeVector(0, 0, -1, 2));
		electronOrbitalMap.put(ChemicalElement.Neodymium, new OrbitalChangeVector(0, 0, 0, 1));
		electronOrbitalMap.put(ChemicalElement.Promethium, new OrbitalChangeVector(0, 0, 0, 1));
		electronOrbitalMap.put(ChemicalElement.Samarium, new OrbitalChangeVector(0, 0, 0, 1));
		electronOrbitalMap.put(ChemicalElement.Europium, new OrbitalChangeVector(0, 0, 0, 1));
		electronOrbitalMap.put(ChemicalElement.Gadolinium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Terbium, new OrbitalChangeVector(0, 0, -1, 2));
		electronOrbitalMap.put(ChemicalElement.Dysprosium, new OrbitalChangeVector(0, 0, 0, 1));
		electronOrbitalMap.put(ChemicalElement.Holmium, new OrbitalChangeVector(0, 0, 0, 1));
		electronOrbitalMap.put(ChemicalElement.Erbium, new OrbitalChangeVector(0, 0, 0, 1));
		electronOrbitalMap.put(ChemicalElement.Thulium, new OrbitalChangeVector(0, 0, 0, 1));
		electronOrbitalMap.put(ChemicalElement.Ytterbium, new OrbitalChangeVector(0, 0, 0, 1));
		electronOrbitalMap.put(ChemicalElement.Lutetium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Hafnium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Tantalum, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Tungsten, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Rhenium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Osmium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Iridium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Platinum, new OrbitalChangeVector(-1, 0, 2, 0));
		electronOrbitalMap.put(ChemicalElement.Gold, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Mercury, new OrbitalChangeVector(1, 0, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Thallium, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Lead, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Bismuth, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Polonium, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Astatine, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Radon, new OrbitalChangeVector(0, 1, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Francium, new OrbitalChangeVector(1, 0, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Radium, new OrbitalChangeVector(1, 0, 0, 0));
		electronOrbitalMap.put(ChemicalElement.Actinium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Thorium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Protactinium, new OrbitalChangeVector(0, 0, -1, 2));
		electronOrbitalMap.put(ChemicalElement.Uranium, new OrbitalChangeVector(0, 0, 0, 1));
		electronOrbitalMap.put(ChemicalElement.Neptunium, new OrbitalChangeVector(0, 0, 0, 1));
		electronOrbitalMap.put(ChemicalElement.Plutonium, new OrbitalChangeVector(0, 0, -1, 2));
		electronOrbitalMap.put(ChemicalElement.Americium, new OrbitalChangeVector(0, 0, 0, 1));
		electronOrbitalMap.put(ChemicalElement.Curium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Berkelium, new OrbitalChangeVector(0, 0, -1, 2));
		electronOrbitalMap.put(ChemicalElement.Californium, new OrbitalChangeVector(0, 0, 0, 1));
		electronOrbitalMap.put(ChemicalElement.Einsteinium, new OrbitalChangeVector(0, 0, 0, 1));
		electronOrbitalMap.put(ChemicalElement.Fermium, new OrbitalChangeVector(0, 0, 0, 1));
		electronOrbitalMap.put(ChemicalElement.Mendelevium, new OrbitalChangeVector(0, 0, 0, 1));
		electronOrbitalMap.put(ChemicalElement.Nobelium, new OrbitalChangeVector(0, 0, 0, 1));
		electronOrbitalMap.put(ChemicalElement.Lawrencium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Rutherfordium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Dubnium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Seaborgium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Bohrium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Hassium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Meitnerium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Darmstadtium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Roentgenium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Ununbium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Ununtrium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Ununquadium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Ununpentiun, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Ununhexium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Ununseptium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Ununoctium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Ununnonium, new OrbitalChangeVector(0, 0, 1, 0));
		electronOrbitalMap.put(ChemicalElement.Unundecium, new OrbitalChangeVector(0, 0, 1, 0));
		return electronOrbitalMap;
	}

	/*
	 * The following HashMap maps element symbols with their corresponding
	 * elements.
	 */
	static HashMap<String, ChemicalElement> symbols() {
		HashMap<String, ChemicalElement> symbols = new HashMap<String, ChemicalElement>();
		symbols.put("H", ChemicalElement.Hydrogen);
		symbols.put("He", ChemicalElement.Helium);
		symbols.put("Li", ChemicalElement.Lithium);
		symbols.put("Be", ChemicalElement.Beryllium);
		symbols.put("B", ChemicalElement.Boron);
		symbols.put("C", ChemicalElement.Carbon);
		symbols.put("N", ChemicalElement.Nitrogen);
		symbols.put("O", ChemicalElement.Oxygen);
		symbols.put("F", ChemicalElement.Fluorine);
		symbols.put("Ne", ChemicalElement.Neon);
		symbols.put("Na", ChemicalElement.Sodium);
		symbols.put("Mg", ChemicalElement.Magnesium);
		symbols.put("Al", ChemicalElement.Aluminum);
		symbols.put("Si", ChemicalElement.Silicon);
		symbols.put("P", ChemicalElement.Phosphorus);
		symbols.put("S", ChemicalElement.Sulfur);
		symbols.put("Cl", ChemicalElement.Chlorine);
		symbols.put("Ar", ChemicalElement.Argon);
		symbols.put("K", ChemicalElement.Potassium);
		symbols.put("Ca", ChemicalElement.Calcium);
		symbols.put("Sc", ChemicalElement.Scandium);
		symbols.put("Ti", ChemicalElement.Titanium);
		symbols.put("Va", ChemicalElement.Vanadium);
		symbols.put("Cr", ChemicalElement.Chromium);
		symbols.put("Mn", ChemicalElement.Manganese);
		symbols.put("Fe", ChemicalElement.Iron);
		symbols.put("Co", ChemicalElement.Cobalt);
		symbols.put("Ni", ChemicalElement.Nickel);
		symbols.put("Cu", ChemicalElement.Copper);
		symbols.put("Zn", ChemicalElement.Zinc);
		symbols.put("Ga", ChemicalElement.Gallium);
		symbols.put("Ge", ChemicalElement.Germanium);
		symbols.put("As", ChemicalElement.Arsenic);
		symbols.put("Se", ChemicalElement.Selenium);
		symbols.put("Br", ChemicalElement.Bromine);
		symbols.put("Kr", ChemicalElement.Krypton);
		symbols.put("Rb", ChemicalElement.Rubidium);
		symbols.put("Sr", ChemicalElement.Strontium);
		symbols.put("Y", ChemicalElement.Yttrium);
		symbols.put("Zr", ChemicalElement.Zirconium);
		symbols.put("Nb", ChemicalElement.Niobium);
		symbols.put("Mo", ChemicalElement.Molybdenum);
		symbols.put("Tc", ChemicalElement.Technetium);
		symbols.put("Ru", ChemicalElement.Ruthenium);
		symbols.put("Rh", ChemicalElement.Rhodium);
		symbols.put("Pd", ChemicalElement.Palladium);
		symbols.put("Ag", ChemicalElement.Silver);
		symbols.put("Cd", ChemicalElement.Cadmium);
		symbols.put("In", ChemicalElement.Indium);
		symbols.put("Sn", ChemicalElement.Tin);
		symbols.put("Sb", ChemicalElement.Antimony);
		symbols.put("Te", ChemicalElement.Tellurium);
		symbols.put("I", ChemicalElement.Iodine);
		symbols.put("Xe", ChemicalElement.Xenon);
		symbols.put("Cs", ChemicalElement.Cesium);
		symbols.put("Ba", ChemicalElement.Barium);
		symbols.put("La", ChemicalElement.Lanthanum);
		symbols.put("Ce", ChemicalElement.Cerium);
		symbols.put("Pr", ChemicalElement.Praseodymium);
		symbols.put("Nd", ChemicalElement.Neodymium);
		symbols.put("Pm", ChemicalElement.Promethium);
		symbols.put("Sm", ChemicalElement.Samarium);
		symbols.put("Eu", ChemicalElement.Europium);
		symbols.put("Gd", ChemicalElement.Gadolinium);
		symbols.put("Tb", ChemicalElement.Terbium);
		symbols.put("Dy", ChemicalElement.Dysprosium);
		symbols.put("Ho", ChemicalElement.Holmium);
		symbols.put("Er", ChemicalElement.Erbium);
		symbols.put("Tm", ChemicalElement.Thulium);
		symbols.put("Yb", ChemicalElement.Ytterbium);
		symbols.put("Lu", ChemicalElement.Lutetium);
		symbols.put("Hf", ChemicalElement.Hafnium);
		symbols.put("Ta", ChemicalElement.Tantalum);
		symbols.put("W", ChemicalElement.Tungsten);
		symbols.put("Re", ChemicalElement.Rhenium);
		symbols.put("Os", ChemicalElement.Osmium);
		symbols.put("Ir", ChemicalElement.Iridium);
		symbols.put("Pt", ChemicalElement.Platinum);
		symbols.put("Au", ChemicalElement.Gold);
		symbols.put("Hg", ChemicalElement.Mercury);
		symbols.put("Tl", ChemicalElement.Thallium);
		symbols.put("Pb", ChemicalElement.Lead);
		symbols.put("Bi", ChemicalElement.Bismuth);
		symbols.put("Po", ChemicalElement.Polonium);
		symbols.put("At", ChemicalElement.Astatine);
		symbols.put("Rn", ChemicalElement.Radon);
		symbols.put("Fr", ChemicalElement.Francium);
		symbols.put("Ra", ChemicalElement.Radium);
		symbols.put("Ac", ChemicalElement.Actinium);
		symbols.put("Th", ChemicalElement.Thorium);
		symbols.put("Pa", ChemicalElement.Protactinium);
		symbols.put("U", ChemicalElement.Uranium);
		symbols.put("Np", ChemicalElement.Neptunium);
		symbols.put("Pu", ChemicalElement.Plutonium);
		symbols.put("Am", ChemicalElement.Americium);
		symbols.put("Cm", ChemicalElement.Curium);
		symbols.put("Bk", ChemicalElement.Berkelium);
		symbols.put("Cf", ChemicalElement.Californium);
		symbols.put("Es", ChemicalElement.Einsteinium);
		symbols.put("Fm", ChemicalElement.Fermium);
		symbols.put("Md", ChemicalElement.Mendelevium);
		symbols.put("No", ChemicalElement.Nobelium);
		symbols.put("Lr", ChemicalElement.Lawrencium);
		symbols.put("Rf", ChemicalElement.Rutherfordium);
		symbols.put("Db", ChemicalElement.Dubnium);
		symbols.put("Sg", ChemicalElement.Seaborgium);
		symbols.put("Bh", ChemicalElement.Bohrium);
		symbols.put("Hs", ChemicalElement.Hassium);
		symbols.put("Mt", ChemicalElement.Meitnerium);
		symbols.put("Ds", ChemicalElement.Darmstadtium);
		symbols.put("Rg", ChemicalElement.Roentgenium);
		symbols.put("Uub", ChemicalElement.Ununbium);
		symbols.put("Uut", ChemicalElement.Ununtrium);
		symbols.put("Uuq", ChemicalElement.Ununquadium);
		symbols.put("Uup", ChemicalElement.Ununpentiun);
		symbols.put("Uuh", ChemicalElement.Ununhexium);
		symbols.put("Uus", ChemicalElement.Ununseptium);
		symbols.put("Uuo", ChemicalElement.Ununoctium);
		symbols.put("Uun", ChemicalElement.Ununnonium);
		symbols.put("Uud", ChemicalElement.Unundecium);
		return symbols;
	}

	static Properties atomicDiameters() {
		Properties atomicDiameters = new Properties();
		atomicDiameters.put(ChemicalElement.Hydrogen, new Integer(53));
		atomicDiameters.put(ChemicalElement.Helium, new Integer(31));
		atomicDiameters.put(ChemicalElement.Lithium, new Integer(167));
		atomicDiameters.put(ChemicalElement.Beryllium, new Integer(112));
		atomicDiameters.put(ChemicalElement.Boron, new Integer(87));
		atomicDiameters.put(ChemicalElement.Carbon, new Integer(67));
		atomicDiameters.put(ChemicalElement.Nitrogen, new Integer(56));
		atomicDiameters.put(ChemicalElement.Oxygen, new Integer(48));
		atomicDiameters.put(ChemicalElement.Fluorine, new Integer(42));
		atomicDiameters.put(ChemicalElement.Neon, new Integer(38));
		atomicDiameters.put(ChemicalElement.Sodium, new Integer(190));
		atomicDiameters.put(ChemicalElement.Magnesium, new Integer(145));
		atomicDiameters.put(ChemicalElement.Aluminum, new Integer(118));
		atomicDiameters.put(ChemicalElement.Silicon, new Integer(111));
		atomicDiameters.put(ChemicalElement.Phosphorus, new Integer(98));
		atomicDiameters.put(ChemicalElement.Sulfur, new Integer(88));
		atomicDiameters.put(ChemicalElement.Chlorine, new Integer(79));
		atomicDiameters.put(ChemicalElement.Argon, new Integer(71));
		atomicDiameters.put(ChemicalElement.Potassium, new Integer(243));
		atomicDiameters.put(ChemicalElement.Calcium, new Integer(194));
		atomicDiameters.put(ChemicalElement.Scandium, new Integer(184));
		atomicDiameters.put(ChemicalElement.Titanium, new Integer(176));
		atomicDiameters.put(ChemicalElement.Vanadium, new Integer(171));
		atomicDiameters.put(ChemicalElement.Chromium, new Integer(166));
		atomicDiameters.put(ChemicalElement.Manganese, new Integer(161));
		atomicDiameters.put(ChemicalElement.Iron, new Integer(156));
		atomicDiameters.put(ChemicalElement.Cobalt, new Integer(152));
		atomicDiameters.put(ChemicalElement.Nickel, new Integer(149));
		atomicDiameters.put(ChemicalElement.Copper, new Integer(145));
		atomicDiameters.put(ChemicalElement.Zinc, new Integer(142));
		atomicDiameters.put(ChemicalElement.Gallium, new Integer(136));
		atomicDiameters.put(ChemicalElement.Germanium, new Integer(125));
		atomicDiameters.put(ChemicalElement.Arsenic, new Integer(114));
		atomicDiameters.put(ChemicalElement.Selenium, new Integer(103));
		atomicDiameters.put(ChemicalElement.Bromine, new Integer(94));
		atomicDiameters.put(ChemicalElement.Krypton, new Integer(88));
		atomicDiameters.put(ChemicalElement.Rubidium, new Integer(265));
		atomicDiameters.put(ChemicalElement.Strontium, new Integer(219));
		atomicDiameters.put(ChemicalElement.Yttrium, new Integer(212));
		atomicDiameters.put(ChemicalElement.Zirconium, new Integer(206));
		atomicDiameters.put(ChemicalElement.Niobium, new Integer(198));
		atomicDiameters.put(ChemicalElement.Molybdenum, new Integer(190));
		atomicDiameters.put(ChemicalElement.Technetium, new Integer(183));
		atomicDiameters.put(ChemicalElement.Ruthenium, new Integer(178));
		atomicDiameters.put(ChemicalElement.Rhodium, new Integer(173));
		atomicDiameters.put(ChemicalElement.Palladium, new Integer(169));
		atomicDiameters.put(ChemicalElement.Silver, new Integer(165));
		atomicDiameters.put(ChemicalElement.Cadmium, new Integer(161));
		atomicDiameters.put(ChemicalElement.Indium, new Integer(156));
		atomicDiameters.put(ChemicalElement.Tin, new Integer(145));
		atomicDiameters.put(ChemicalElement.Antimony, new Integer(133));
		atomicDiameters.put(ChemicalElement.Tellurium, new Integer(123));
		atomicDiameters.put(ChemicalElement.Iodine, new Integer(115));
		atomicDiameters.put(ChemicalElement.Xenon, new Integer(108));
		atomicDiameters.put(ChemicalElement.Cesium, new Integer(298));
		atomicDiameters.put(ChemicalElement.Barium, new Integer(253));
		atomicDiameters.put(ChemicalElement.Lanthanum, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Cerium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Praseodymium, new Integer(247));
		atomicDiameters.put(ChemicalElement.Neodymium, new Integer(206));
		atomicDiameters.put(ChemicalElement.Promethium, new Integer(205));
		atomicDiameters.put(ChemicalElement.Samarium, new Integer(238));
		atomicDiameters.put(ChemicalElement.Europium, new Integer(231));
		atomicDiameters.put(ChemicalElement.Gadolinium, new Integer(233));
		atomicDiameters.put(ChemicalElement.Terbium, new Integer(225));
		atomicDiameters.put(ChemicalElement.Dysprosium, new Integer(228));
		atomicDiameters.put(ChemicalElement.Holmium, new Integer(226));
		atomicDiameters.put(ChemicalElement.Erbium, new Integer(226));
		atomicDiameters.put(ChemicalElement.Thulium, new Integer(222));
		atomicDiameters.put(ChemicalElement.Ytterbium, new Integer(222));
		atomicDiameters.put(ChemicalElement.Lutetium, new Integer(217));
		atomicDiameters.put(ChemicalElement.Hafnium, new Integer(208));
		atomicDiameters.put(ChemicalElement.Tantalum, new Integer(200));
		atomicDiameters.put(ChemicalElement.Tungsten, new Integer(193));
		atomicDiameters.put(ChemicalElement.Rhenium, new Integer(188));
		atomicDiameters.put(ChemicalElement.Osmium, new Integer(185));
		atomicDiameters.put(ChemicalElement.Iridium, new Integer(180));
		atomicDiameters.put(ChemicalElement.Platinum, new Integer(177));
		atomicDiameters.put(ChemicalElement.Gold, new Integer(174));
		atomicDiameters.put(ChemicalElement.Mercury, new Integer(171));
		atomicDiameters.put(ChemicalElement.Thallium, new Integer(156));
		atomicDiameters.put(ChemicalElement.Lead, new Integer(154));
		atomicDiameters.put(ChemicalElement.Bismuth, new Integer(143));
		atomicDiameters.put(ChemicalElement.Polonium, new Integer(135));
		atomicDiameters.put(ChemicalElement.Astatine, new Integer(127));
		atomicDiameters.put(ChemicalElement.Radon, new Integer(120));
		atomicDiameters.put(ChemicalElement.Francium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Radium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Actinium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Thorium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Protactinium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Uranium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Neptunium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Plutonium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Americium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Curium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Berkelium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Californium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Einsteinium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Fermium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Mendelevium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Nobelium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Lawrencium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Rutherfordium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Dubnium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Seaborgium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Barium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Hassium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Meitnerium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Darmstadtium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Roentgenium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Ununbium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Ununtrium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Ununquadium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Ununpentiun, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Ununhexium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Ununseptium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Ununoctium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Ununnonium, new Integer(1000));
		atomicDiameters.put(ChemicalElement.Unundecium, new Integer(1000));
		return atomicDiameters;
	}
}
